francoralite/apps/francoralite_front/urls.py
# -*- coding: utf-8 -*-
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Authors: Luc LEGER / Coopérative ARTEFACTS <artefacts.lle@gmail.com>

from django.conf.urls import re_path, include

from .views import (
    home as home_integration,
    institution, institution_add, institution_delete, institution_detail,
    institution_edit,
    personne, personne_add, personne_detail, personne_edit, personne_delete,
    personne_collector, personne_informer, personne_author, personne_composer,
    personne_editor,
    location, location_add, location_detail, location_edit, location_delete,
    location_gis, location_gis_add, location_gis_detail, location_gis_edit,
    location_gis_delete,
    location_gis_collection,
    fond, fond_add, fond_detail, fond_edit, fond_delete,
    mission, mission_add, mission_detail, mission_edit, mission_delete,
    collection, collection_add, collection_detail, collection_edit,
    collection_delete,
    item, item_add, item_detail, item_edit,
    item_delete,
    search as search_integration,
    search_advanced,
)

from .views.enum import (
    block, block_edit, block_delete, block_detail, block_add,
    civility, civility_edit, civility_delete, civility_detail, civility_add,
    cultural_area, cultural_area_edit, cultural_area_delete,
    cultural_area_detail, cultural_area_add,
    instrument, instrument_edit, instrument_delete, instrument_detail,
    instrument_add,
    domain_song, domain_song_edit, domain_song_delete, domain_song_detail,
    domain_song_add,
    domain_music, domain_music_edit, domain_music_delete, domain_music_detail,
    domain_music_add,
    domain_tale, domain_tale_edit, domain_tale_delete, domain_tale_detail,
    domain_tale_add,
    domain_vocal, domain_vocal_edit, domain_vocal_delete, domain_vocal_detail,
    domain_vocal_add,
    dance, dance_edit, dance_delete, dance_detail,
    dance_add,
    emit_vox, emit_vox_edit, emit_vox_delete, emit_vox_detail,
    emit_vox_add,
    keyword, keyword_edit, keyword_delete, keyword_detail, keyword_add,
    language, language_edit, language_delete, language_detail, language_add,
    musical_organization, musical_organization_edit,
    musical_organization_delete, musical_organization_detail,
    musical_organization_add,
    hornbostelsachs, hornbostelsachs_edit, hornbostelsachs_delete,
    hornbostelsachs_detail, hornbostelsachs_add,
    musical_group, musical_group_edit,
    musical_group_delete, musical_group_detail,
    musical_group_add,
    thematic, thematic_edit, thematic_delete, thematic_detail,
    thematic_add,
    coirault,coirault_detail,
    usefulness, usefulness_edit, usefulness_delete, usefulness_detail,
    usefulness_add,
    coupe, coupe_edit, coupe_delete, coupe_detail,
    coupe_add,
    legal_rights, legal_rights_edit, legal_rights_delete, legal_rights_detail,
    legal_rights_add,
    mediatype, mediatype_edit, mediatype_delete, mediatype_detail,
    mediatype_add,
    metadata_author, metadata_author_edit, metadata_author_delete,
    metadata_author_detail, metadata_author_add,
    publisher, publisher_edit, publisher_delete, publisher_detail,
    publisher_add,
    recording_context, recording_context_edit, recording_context_delete,
    recording_context_detail, recording_context_add,
    ref_laforte, ref_laforte_edit, ref_laforte_delete, ref_laforte_detail,
    ref_laforte_add,
)


urlpatterns = [
    re_path(r'^$', home_integration.HomePageView.as_view(), name="home"),
    re_path(r'^select2/', include('django_select2.urls')),
    re_path(r'^search/', search_integration.SearchView.as_view(),
        name="search-simple"),
    re_path(r'^search_advanced/', search_advanced.SearchAdvancedView.as_view(),
        name="search-advanced"),

    # Institutions
    re_path(r'^institution$', institution.InstitutionView.as_view(),
        name="institution"),
    re_path(r'^institution/(?P<id>[0-9]+)$',
        institution_detail.InstitutionDetail.as_view(),
        name='institution-detail'),
    re_path(r'^institution/add$',
        institution_add.InstitutionAdd.as_view(),
        name='institution-add'),
    re_path(r'^institution/edit/(?P<id>[0-9]+)$',
        institution_edit.InstitutionEdit.as_view(),
        name='institution-edit'),
    re_path(r'^institution/delete/(?P<id>[0-9]+)$',
        institution_delete.InstitutionDelete.as_view(),
        name='institution-delete'),

    # Authority  (Personnes)
    re_path(r'^authority$', personne.PersonneView.as_view(),
        name="personne"),
    re_path(r'^authority/add$',
        personne_add.PersonneAdd.as_view(),
        name='personne-add'),
    re_path(r'^authority/(?P<id>[0-9]+)$',
        personne_detail.PersonneDetail.as_view(),
        name='personne-detail'),
    re_path(r'^authority/edit/(?P<id>[0-9]+)$',
        personne_edit.PersonneEdit.as_view(),
        name='personne-edit'),
    re_path(r'^authority/delete/(?P<id>[0-9]+)$',
        personne_delete.PersonneDelete.as_view(),
        name='personne-delete'),
    re_path(r'^authority_collector$',
        personne_collector.PersonneCollectorView.as_view(),
        name="personne-collector"),
    re_path(r'^authority_informer$',
        personne_informer.PersonneInformerView.as_view(),
        name="personne-informer"),
    re_path(r'^authority_author$',
        personne_author.PersonneAuthorView.as_view(),
        name="personne-author"),
    re_path(r'^authority_composer$',
        personne_composer.PersonneComposerView.as_view(),
        name="personne-composer"),
    re_path(r'^authority_editor$',
        personne_editor.PersonneEditorView.as_view(),
        name="personne-editor"),

    # Blocks
    re_path(r'^block$', block.BlockView.as_view(),
        name="block"),
    re_path(r'^block/add$',
        block_add.BlockAdd.as_view(),
        name='block-add'),
    re_path(r'^block/(?P<id>[0-9]+)$',
        block_detail.BlockDetail.as_view(),
        name='block-detail'),
    re_path(r'^block/edit/(?P<id>[0-9]+)$',
        block_edit.BlockEdit.as_view(),
        name='block-edit'),
    re_path(r'^block/delete/(?P<id>[0-9]+)$',
        block_delete.BlockDelete.as_view(),
        name='block-delete'),

    # Civilities
    re_path(r'^civility$', civility.CivilityView.as_view(),
        name="civility"),
    re_path(r'^civility/add$',
        civility_add.CivilityAdd.as_view(),
        name='civility-add'),
    re_path(r'^civility/(?P<id>[0-9]+)$',
        civility_detail.CivilityDetail.as_view(),
        name='civility-detail'),
    re_path(r'^civility/edit/(?P<id>[0-9]+)$',
        civility_edit.CivilityEdit.as_view(),
        name='civility-edit'),
    re_path(r'^civility/delete/(?P<id>[0-9]+)$',
        civility_delete.CivilityDelete.as_view(),
        name='civility-delete'),

    # Civilities
    re_path(r'^cultural_area$', cultural_area.CulturalAreaView.as_view(),
        name="cultural_area"),
    re_path(r'^cultural_area/add$',
        cultural_area_add.CulturalAreaAdd.as_view(),
        name='cultural_area-add'),
    re_path(r'^cultural_area/(?P<id>[0-9]+)$',
        cultural_area_detail.CulturalAreaDetail.as_view(),
        name='cultural_area-detail'),
    re_path(r'^cultural_area/edit/(?P<id>[0-9]+)$',
        cultural_area_edit.CulturalAreaEdit.as_view(),
        name='cultural_area-edit'),
    re_path(r'^cultural_area/delete/(?P<id>[0-9]+)$',
        cultural_area_delete.CulturalAreaDelete.as_view(),
        name='cultural_area-delete'),

    # Location ( Lieux)
    re_path(r'^location$', location.LocationView.as_view(),
        name="location"),
    re_path(r'^location/add$',
        location_add.LocationAdd.as_view(),
        name='location-add'),
    re_path(r'^location/(?P<id>[0-9]+)$',
        location_detail.LocationDetail.as_view(),
        name='location-detail'),
    re_path(r'^location/edit/(?P<id>[0-9]+)$',
        location_edit.LocationEdit.as_view(),
        name='location-edit'),
    re_path(r'^location/delete/(?P<id>[0-9]+)$',
        location_delete.LocationDelete.as_view(),
        name='location-delete'),

    # Location GIS ( Lieux)
    re_path(r'^location_gis/$', location_gis.LocationView.as_view(),
        name="location_gis"),
    re_path(r'^location_gis/add$',
        location_gis_add.LocationAdd.as_view(),
        name='location_gis-add'),
    re_path(r'^location_gis/(?P<id>[0-9]+)$',
        location_gis_detail.LocationDetail.as_view(),
        name='location_gis-detail'),
    re_path(r'^location_gis/edit/(?P<id>[0-9]+)$',
        location_gis_edit.LocationEdit.as_view(),
        name='location_gis-edit'),
    re_path(r'^location_gis/delete/(?P<id>[0-9]+)$',
        location_gis_delete.LocationDelete.as_view(),
        name='location_gis-delete'),
    re_path(r'^location_gis_collection$',
        location_gis_collection.LocationCollectionView.as_view(),
        name="location_gis-collection"),

    # Fonds
    re_path(r'^fond$', fond.FondView.as_view(),
        name="fond"),
    re_path(r'^institution/(?P<id_institution>[0-9]+)/fond/add$',
        fond_add.FondAdd.as_view(),
        name='fond-add'),
    re_path(r'^fond/(?P<id>[0-9]+)$',
        fond_detail.FondDetail.as_view(),
        name='fond-detail'),
    re_path(r'^fond/edit/(?P<id>[0-9]+)$',
        fond_edit.FondEdit.as_view(),
        name='fond-edit'),
    re_path(r'^fond/delete/(?P<id>[0-9]+)$',
        fond_delete.FondDelete.as_view(),
        name='fond-delete'),

    # Mission
    re_path(r'^mission$', mission.MissionView.as_view(),
        name="mission"),
    re_path(r'^institution/(?P<id_institution>[0-9]+)/fond/(?P<id_fond>[0-9]+)/mission/add$',  # noqa
        mission_add.MissionAdd.as_view(),
        name='mission-add'),
    re_path(r'^mission/(?P<id>[0-9]+)$',
        mission_detail.MissionDetail.as_view(),
        name='mission-detail'),
    re_path(r'^mission/edit/(?P<id>[0-9]+)$',
        mission_edit.MissionEdit.as_view(),
        name='mission-edit'),

francoralite/urls.py
import os

from django.conf import settings
from django.conf.urls import re_path, include
#from django.contrib import admin
from django.http import HttpResponse
#from django.views.i18n import javascript_catalog

from rest_framework import permissions
from rest_framework.schemas import get_schema_view

# OpenAPI
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

# Apps urls
from .apps.francoralite_api import urls as francoralite_api_urls
from .apps.francoralite_front import urls as francoralite_front_urls
from .apps.francoralite_front.views.errors import (
    handler400, handler403, handler404, handler500)

# AuthenticationFailed
import mozilla_django_oidc.urls

# OpenAPI management
schema_view = get_schema_view(
   openapi.Info(
      title="Francoralite API",
      default_version='v1',
      description="Francoralite API",
      terms_of_service="https://francoralite.net/legal/", # FIXME: A valider !
      contact=openapi.Contact(email="contact@francoralite.net"),
      license=openapi.License(name="MIT License"), # FIXME: A valider !
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

# admin.autodiscover()

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
robots_rules = open(PROJECT_ROOT + os.sep + 'robots.txt', 'r').read()

urlpatterns = [
    # New frontend endpoints
    re_path(r'', include(francoralite_front_urls)),

#    re_path(r'^admin/django/', include(admin.site.urls)),
    re_path(r'^', include(francoralite_api_urls)),
    re_path(r'^api/', include(francoralite_api_urls.router.urls)),
    re_path(r'^api/', include(francoralite_api_urls.authority_router.urls)),
    re_path(r'^api/', include(francoralite_api_urls.fond_router.urls)),
    re_path(r'^api/', include(francoralite_api_urls.mission_router.urls)),
    re_path(r'^api/', include(francoralite_api_urls.collection_router.urls)),
    re_path(r'^api/', include(francoralite_api_urls.performance_router.urls)),
    re_path(r'^api/', include(francoralite_api_urls.item_router.urls)),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    re_path(r'^oidc/', include(mozilla_django_oidc.urls)),

    # Languages
#    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r'^robots\.txt$', lambda r: HttpResponse(
        robots_rules, content_type="text/plain")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ]

francoralite/apps/francoralite_api/models/institution.py
# -*- coding: utf-8 -*-
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Authors: Luc LEGER / Cooperative Artefacts <artefacts.lle@gmail.com>


from django.db import models
from django.utils.translation import gettext_lazy as _


class Institution(models.Model):
    "Institution who owns some resources"

    name = models.CharField(_('name'), max_length=255)
    notes = models.TextField(_('notes'), null=True, blank=True)


    class Meta:
        app_label = 'francoralite_api'
        db_table = 'institutions'
        verbose_name_plural = _('institutions')
        ordering = ['name']

    def __unicode__(self):
        return self.name

francoralite/apps/francoralite_front/forms/block.py
# -*- coding: utf-8 -*-
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Authors: Luc LEGER / Coopérative ARTEFACTS <artefacts.lle@gmail.com>

from django import forms
from django.utils.translation import gettext_lazy as _

from francoralite.apps.francoralite_front import tools
from django.core.exceptions import ValidationError


class BlockForm(forms.Form):

    TYPE_CUSTOM_TEXT = None
    TYPE_MAP = 'M'
    TYPE_PARTNERS = 'P'
    TYPE_CHOICES = (
        (TYPE_CUSTOM_TEXT, _('Texte personnalisé')),
        (TYPE_MAP, _('Carte')),
        (TYPE_PARTNERS, _('Partenaires')),
    )

    type = forms.ChoiceField(label=_(u'Type'),
        choices=TYPE_CHOICES, required=False)
    title = forms.CharField(label=_(u'Titre'),
        max_length=255, required=True)
    content = forms.CharField(label=_(u'Contenu'),
        widget=forms.Textarea, required=False)
    order = forms.IntegerField(label=_(u'Ordre d’affichage'),
        widget=forms.NumberInput, min_value=1, required=True)
    show = forms.BooleanField(label=_(u'Afficher'),
        required=False)

    def __init__(self, *args, **kwargs):
        super(BlockForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()

        if cleaned_data.get('type') and cleaned_data.get('content'):
            self.add_error('type', ValidationError(
                _('Un bloc de ce type ne peut pas avoir un contenu personnalisé.')))

        for block in tools.request_api('/api/block'):
            if block.get('id') == getattr(self, 'current_id', None):
                continue

            block_title = cleaned_data.get('title')
            if block_title and block.get('title') == block_title:
                self.add_error('title', ValidationError(
                    _('Un bloc avec ce titre existe déjà.')))

            block_type = cleaned_data.get('type')
            if block_type and block.get('type') == block_type:
                self.add_error('type', ValidationError(
                    _('Un bloc de ce type existe déjà.')))

            block_order = cleaned_data.get('order')
            if block_order and block.get('order') == block_order:
                self.add_error('order', ValidationError(
                    _('Un bloc avec cet ordre d’affichage existe déjà.')))

        return cleaned_data

francoralite/apps/francoralite_front/forms/civility.py
# -*- coding: utf-8 -*-
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Authors: Luc LEGER / Coopérative ARTEFACTS <artefacts.lle@gmail.com>

from django import forms
from django.utils.translation import gettext_lazy as _


class CivilityForm(forms.Form):
    name = forms.CharField(
        label=_(u'Nom'),
        max_length=255, required=True)

    def __init__(self, *args, **kwargs):
        super(CivilityForm, self).__init__(*args, **kwargs)

francoralite/apps/francoralite_front/forms/coirault.py
# -*- coding: utf-8 -*-
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Authors: Luc LEGER / Coopérative ARTEFACTS <artefacts.lle@gmail.com>

from django import forms
from django.utils.translation import gettext_lazy as _


class CoiraultForm(forms.Form):
    number = forms.CharField(
        label=_(u'Numérotation'),
        max_length=40, required=True)
    name = forms.CharField(
        label=_(u'Chanson-type'),
        max_length=500, required=True)
    uri = forms.CharField(
        label=_(u'URI'),
        max_length=500, required=True)
    abstract = forms.CharField(
        label=_(u'Résumé'),
        widget=forms.Textarea, required=False)

    def __init__(self, *args, **kwargs):
        super(CoiraultForm, self).__init__(*args, **kwargs)

francoralite/apps/francoralite_front/templates/collection.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load markdown_extra %}
{% load data_display %}


{% block javascript %}
  {{ block.super }}
{% endblock %}


{% block stylesheets %}
  {{ block.super }}
{% endblock %}


{% block title_name %}
  {% trans "Enquêtes" %}
{% endblock %}


{% block content %}

{% block title %}
{{ block.super }}
{% endblock %}

{% block title_buttons %}
{% endblock %}

<div class="fullpage">
{% if collections|length > 0 %}
  <!-- Table to display the collections -->
  <table class="listing">
  <thead>
  <tr>
      {% include "inc/sortable-table-column-header.html" with field="code" label=_("Cote") highlight=True %}
      {% include "inc/sortable-table-column-header.html" with field="title" label=_("Nom") %}
      {% include "inc/sortable-table-column-header.html" with field="description" label=_("Description") %}
      {% include "inc/sortable-table-column-header.html" with field="items_count" label=_("Items") %}
      <th>{% trans "Domaines" %}</th>
      {% if perms.keycloak.collection_update or perms.keycloak.collection_delete %}
      <th>{% trans "Modifier" %}</th>
      {% endif %}
  </tr>
  </thead>
  <tbody>
  {% for collection in collections %}
  <tr>
      <td class="highlight">
          <a href="/collection/{{collection.id }}">
            {{ collection.code|upper }}</a>
      </td>
      <td>{{ collection.title|safe }}</td>
      <td>{{ collection.description|truncatechars:50|markdown|safe }}</td>
      <td><a href="/collection/{{ collection.id }}#items">{{ collection.items_count }}</a></td>
      <td>{% include 'inc/proportional_colored_bar.html' with items=collection.domains %}</td>
      {% if perms.keycloak.collection_update or perms.keycloak.collection_delete %}
      <td>
      {% if perms.keycloak.collection_update %}
        <a href="{% url "collection-edit" id=collection.id %}" class="btn btn-default">
          <span class="glyphicon glyphicon-edit"></span> {% trans "Éditer" %}
        </a>
      {% endif %}
      {% if perms.keycloak.collection_delete %}
        <button type="button" class="btn btn-default"
            data-toggle="modal" data-target="#modalDelete"
            data-name="{{collection.title}}"
            data-url="{% url "collection-delete" id=collection.id %}">
              <span class="glyphicon glyphicon-trash"></span> {% trans "Supprimer" %}
        </button>
      {% endif %}
      </td>
      {% endif %}
  </tr>
  {% endfor %}
  </tbody>
</table>
{% include 'inc/proportional_colored_bar.html' with legend=domains_legend %}

{% if perms.keycloak.collection_delete %}
    {% modal_delete %}
{% endif %}

{% else %}
  {% if error|length %}
    {% display_error error %}
  {% else %}
    <p>{% trans "Il n'y a pas d'enquêtes" %}</p>
  {% endif %}
{% endif %}
</div>
{% endblock %}

francoralite/apps/francoralite_front/templates/institution-add.html
{% extends "institution.html" %}
{% load i18n %}
{% load data_display %}
{% load markdown_extra %}

{% block javascript %}
  {{ block.super }}
{% endblock %}

{% block stylesheets %}
  {{ block.super }}
{% endblock %}

{% block title_name %}
   {{ block.super}} -
   {% if id %}
   {% trans "Modification" %}
   {% else %}
   {% trans "Création" %}
   {% endif %}
{% endblock %}

{% block content %}

{% block title_buttons %}
{% endblock %}

{% block title %}
{{ block.super }}
{% endblock %}

{% if not error|length %}
  <div class="container">
    {% if id %}
    <form action="{% url "institution-edit" id %}" method="POST">
    {% else %}
    <form action="{{request.path}}" method="POST">
    {% endif %}
      {% csrf_token %}
      {% field_editor form.name %}
      {% markdown_editor component=form.notes  %}

      {% buttons_form %}
    </form>
  </div>

{% else %}
  {% display_error error %}
{% endif %}
{% endblock %}

francoralite/apps/francoralite_front/templates/institution-detail.html
{% extends "institution.html" %}
{% load i18n %}
{% load static %}
{% load markdown_extra %}
{% load data_display %}

{% block javascript %}
  {{ block.super }}
  <script src="{% static "francoralite_front/js/table_sort.js" %}" defer></script>
{% endblock %}


{% block stylesheets %}
  {{ block.super }}
{% endblock %}



{% block title_name %}
  {% trans "Institution" %}
  {% if institution %}
   : {{ institution.name }}
  {% endif %}
{% endblock %}


{% block content %}

{% block title_buttons %}
  {% if perms.keycloak.fond_add %}
    <a href="{% url "fond-add" id_institution=institution.id %}" class="btn_add btn btn-default"><span class="glyphicon glyphicon-plus"></span>{% trans "Créer un fonds" %}</a>
  {% endif %}
  {% if perms.keycloak.institution_update %}
    <a href="{% url "institution-edit" id=id %}" class="btn_add btn btn-default">
        <span class="glyphicon glyphicon-edit"></span>{% trans "Modifier" %}
    </a>
  {% endif %}
{% endblock %}

{% block title %}
  {{ block.super }}
{% endblock %}

{% if not error|length %}
  {% if institution %}
  <p id="id_notes">{{institution.notes|markdown|safe}}</p>

    {% if fonds|length > 0 %}
    <div class="with-rightcol">
      <table class="listing">
      <thead>
          <th class="sortable highlight">{% trans "Cote" %}</th>
          <th class="sortable">{% trans "Nom" %}</th>
          <th class="sortable">{% trans "Description" %}</th>
          {% if perms.keycloak.fond_update or perms.keycloak.fond_delete %}
          <th>{% trans "Modifier" %}</th>
          {% endif %}
      </thead>
      {% for fond in fonds %}
        <tr>
            <td class="highlight">
                <a href="/fond/{{ fond.id }}">
                  {{ fond.code|upper|safe }}</a>
            </td>
            <td>{{ fond.title|safe }}</td>
            <td>
              {% if fond.description %}
              {{ fond.description|markdown|safe }}
              {% endif %}
            </td>
            {% if perms.keycloak.fond_update or perms.keycloak.fond_delete %}
            <td>
              {% if perms.keycloak.fond_update %}
                <a href="{% url "fond-edit" id=fond.id %}">
                      <button type="button" class="btn btn-default">
                        <span class="glyphicon glyphicon-edit"></span> {% trans "Éditer" %}
                      </button>
                </a>
              {% endif %}
              {% if perms.keycloak.fond_delete %}
                <button type="button" class="btn btn-default"
                    data-toggle="modal" data-target="#modalDelete"
                    data-name="{{fond.title}}"
                    data-url="{% url "fond-delete" id=fond.id %}">
                      <span class="glyphicon glyphicon-trash"></span> {% trans "Supprimer" %}
                </button>
              {% endif %}
            </td>
            {% endif %}
          </tr>
        {% endfor %}
      </table>
      </div>

{% if perms.keycloak.fond_delete %}
    {% modal_delete %}
{% endif %}
    {% else %}
      {% trans "Il n'a pas de fonds pour cette institution." %}
    {% endif %}
  {% else %}
    <p>{% trans "Cette institution n'existe pas." %}</p>
  {% endif %}
{% else %}
    {% display_error error %}
{% endif %}
{% endblock %}

francoralite/apps/francoralite_front/templates/location-add.html
{% extends "location.html" %}
{% load i18n %}
{% load data_display %}
{% load markdown_extra %}
{% load static %}

{% block javascript %}
  {{ block.super }}
  <script type="module" src="{% static "francoralite_front/js/webcomponents/map.js" %}"></script>
{% endblock %}

{% block stylesheets %}
  {{ block.super }}
  <style>
    francoralite-map {
      height: 500px;
      width: 100%;
      display: inline-block;
    }
   </style>
{% endblock %}

{% block title_name %}
   {{ block.super}} -
   {% if id %}
   {% trans "Modification" %}
   {% else %}
   {% trans "Création" %}
   {% endif %}
{% endblock %}

{% block content %}

{% block title_buttons %}
{% endblock %}

{% block title %}
  {{ block.super }}
{% endblock %}

{{ form.media }}
<div class="container">
  {% if id %}
  <form action="{%url "location_gis-edit" id %}" method="POST">
  {% else %}
  <form action="{%url "location_gis-add" %}" method="POST">
  {% endif %}
    {% csrf_token %}
    <div>
      <div class="control-label">
        <label class="" for="id_name">{% trans "Carte" %}:</label>
      </div>
      <!-- The map -->
      <francoralite-map markers-drag="yes"
      {% if id %}markers-url="/api/locationgis/{{id}}"{% endif %}>
      </francoralite-map>
    </div>
    <div class="block-grey">
      <h2>{% trans "Coordonnées" %}</h2>
      <div class="container_line">
        {% field_editor form.latitude %}
        {% field_editor form.longitude %}
      </div>
    </div>
    <div class="container_line">
        {% field_editor form.code %}
        {% field_editor form.name %}
    </div>
    <div >
      {% markdown_editor component=form.notes %}
    </div>
      {% buttons_form %}
  </form>
</div>


{% endblock %}

francoralite/apps/francoralite_front/templates/location_collection.html
{% extends "location.html" %}
{% load i18n %}


{% block title_name %}
{% trans "Lieux, par enquêtes" %}
{% endblock %}

{% block request_location %}
<francoralite-map markers-url="/api/locationgiscollection/"></francoralite-map>
{% endblock request_location %}

francoralite/apps/francoralite_front/templates/personne_collector.html
{% extends "personne.html" %}
{% load i18n %}

{% block javascript %}
  {{ block.super }}
{% endblock %}


{% block stylesheets %}
  {{ block.super }}
{% endblock %}

{% block title_name %}
{% trans "Enquêteurs" %}
{% endblock %}

{% block content %}
  {{ block.super }}
{% endblock %}